# Generated by Django 5.1.1 on 2024-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_Documento', models.CharField(verbose_name=40)),
                ('Titulo', models.TextField()),
                ('Autor', models.TextField()),
                ('Biblioteca_material', models.CharField(verbose_name=40)),
                ('Fecha_prestamo', models.DateTimeField(blank=True, null=True)),
                ('Fecha_devolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporal_etl',
            },
        ),
    ]
