# Generated by Django 5.1.1 on 2024-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_prestamo_nro_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Autor',
            field=models.TextField(verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Biblioteca_material',
            field=models.CharField(max_length=40, verbose_name='biblioteca_material'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_devolucion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Titulo',
            field=models.TextField(verbose_name='titulo'),
        ),
    ]
