# Generated by Django 5.1.1 on 2024-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_alter_prestamo_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Autor',
            field=models.TextField(db_column='autor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Biblioteca_material',
            field=models.CharField(db_column='biblioteca_material', max_length=40),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_devolucion',
            field=models.DateTimeField(blank=True, db_column='fecha_devolucion', null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateTimeField(blank=True, db_column='fecha_prestamo', null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Nro_Documento',
            field=models.CharField(db_column='nro_documento', max_length=40),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Titulo',
            field=models.TextField(db_column='titulo'),
        ),
    ]
