# Generated by Django 5.1.1 on 2024-09-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_alter_prestamo_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='Biblioteca_material',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='Fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='Fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='Nro_Documento',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='Titulo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='autor',
            field=models.TextField(blank=True, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='biblioteca_material',
            field=models.CharField(blank=True, max_length=40, verbose_name='biblioteca_material'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_devolucion'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_prestamo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nro_documento',
            field=models.CharField(blank=True, max_length=40, verbose_name='nro_documento'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='titulo',
            field=models.TextField(blank=True, verbose_name='titulo'),
        ),
    ]
