# Generated by Django 5.1.1 on 2024-09-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_remove_prestamo_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='autor',
            field=models.TextField(blank=True, null=True, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='biblioteca_material',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='biblioteca_material'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='nro_documento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='nro_documento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='titulo',
            field=models.TextField(blank=True, null=True, verbose_name='titulo'),
        ),
    ]
